SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE comment;
TRUNCATE TABLE comment_like;
TRUNCATE TABLE follow;
TRUNCATE TABLE password_history;
TRUNCATE TABLE post;
TRUNCATE TABLE post_like;
TRUNCATE TABLE user;
SET FOREIGN_KEY_CHECKS = 1;
